version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: task-manager-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: cdSynthesis
      MONGO_REPLICA_SET_NAME: rs0
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    networks:
      - production-network

  backend:
    build: .
    container_name: my_api
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - production-network
    volumes:
      - ./:/app
    
  frontend:
    build: 
      context: ../Task Manager Frontend # Diretório do Dockerfile do frontend
    container_name: my_frontend
    ports:
      - "8080:8080" # Porta do frontend (host:container)
    networks:
      - production-network
volumes:
  data:

networks:
  production-network:
    driver: bridge

