version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: task-manager-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: cdSynthesis
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

volumes:
  data:
